### ISSUE TITLE
Redemption problem

### ISSUE THREAD

**Issue by thiagomhk** [PACCommunity/PAC#21]
Hello, i made a redemption test following the guide on paccoin.net
But i havent received my new pac

Status: 1070 confirmações
Data: 20/02/2018 23:15
Para: red B3zGATXPtNRbHCeAmhH1sFTb4f2RQJW6nS
Débito: -1000.00 PAC
Taxa de transação: -0.0001 PAC
Valor líquido: -1000.0001 PAC
ID da transação: 1a237dbe8669d47660d3d5854fb82c27665a394a91fa4267ae3f2366f2b66d21
Transaction comment:
text:PTpCRcyrgFNfnexKd3w7dPJrYNQTkwPz1g

**Comment by alejandromgk** [comment]
Hi please send an email to: support@paccoin.net with your issue.
