### ISSUE TITLE
Propositions are broken.

### ISSUE THREAD

**Issue by breakcrypto** [PACCommunity/PAC#25]
It's currently impossible to issue a proposition.

**Comment by alejandromgk** [comment]
Can you share your proposal hex data? What error are you getting?

**Comment by alejandromgk** [comment]
I was able to successfuly submit a proposal: 

`gobject get a0867ba4cdd432491f6fed9391eb21bc9a874e12b09eda1e5ebc3429cf899ac3`

Next superblock will be generated aproximately on March 21st so take that in mind when submiting proposals. End date should be after the next superblock date.

**Comment by tylerpitchford-mlabs** [comment]
Sorry, I should have been more clear; there was no issue submitted the prop but the gobject is being rejected after it's placed on the network.

**Comment by breakcrypto** [comment]
It appears that gobject has gone missing like the others previously submitted:

```
gobject get a0867ba4cdd432491f6fed9391eb21bc9a874e12b09eda1e5ebc3429cf899ac3

Unknown governance object (code -8)
```

This is what I have observed previously.

**Comment by alejandromgk** [comment]
You are right, the proposals are being deleted. Working on this.

**Comment by alejandromgk** [comment]
After the update on: https://github.com/PACCommunity/PAC/pull/27 regarding sentinel ping and https://github.com/PACCommunity/sentinel/pull/4, I can confirm that proposals no longer get deleted automatically, and more importantly, they get paid once they reach the minimum `YES` votes.

I'm gonna keep this open until we can be sure that this also is fixed on Mainnet.

**Comment by alejandromgk** [comment]
Closing this, as proposals are being paid correctly now.
