### ISSUE TITLE
Date range transaction filter. Dates are black on black.

### ISSUE THREAD

**Issue by iamunick** [PACCommunity/PAC#77]
Cannot see the `weekdays` dates of the active month in the date picker since those dates are black and the background is black.

Fix: put the dates white for the active month

**Comment by Ciip1996** [comment]
Hi @iamunick  could you please provide a screen shot and be more specific in which section of the wallet are you having this issue? Thanks

**Comment by iamunick** [comment]
Sure, on the transaction history screen, filter by range

![Screen Shot 2019-04-23 at 1 48 16 PM](https://user-images.githubusercontent.com/10983565/56603832-81fcaf80-65ce-11e9-815d-df6a30af7eb8.png)

**Comment by Ciip1996** [comment]
@iamunick  Thanks again for the feedback. We are looking forward to fix this issue!

**Comment by Ciip1996** [comment]
This issue has been fixed with the new wallet version to be released on May 2019.
